version: "2"

linters:
  default: all
  disable:
    - copyloopvar
    - err113 # WARN [lintersdb] The name "goerr113" is deprecated. The linter has been renamed to: err113
    - tagliatelle
    - wsl
    - nlreturn
    - lll
    - godot
    - varnamelen
    - ireturn
    - depguard
    - tagalign
    # TODO
    - dupl
    - wrapcheck
    - testpackage
    - godox
    - nestif
    - funlen
    - gocognit
    - gocyclo
    - exhaustruct
    - dupword
    - musttag
    - forbidigo
    # tentative
    - revive
    - unparam
    - forcetypeassert
    - noctx
    - perfsprint
    - prealloc
    - mnd
  settings:
    cyclop:
      max-complexity: 12
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
