version: 2
linters:
  enable-all: true
  disable:
    - copyloopvar
    - err113 # WARN [lintersdb] The name "goerr113" is deprecated. The linter has been renamed to: err113
    - tagliatelle
    - wsl
    - nlreturn
    - lll
    - godot
    - varnamelen
    - ireturn
    - depguard
    - tagalign
    # TODO
    - dupl
    - wrapcheck
    - testpackage
    - godox
    - nestif
    - funlen
    - gocognit
    - gocyclo
    - exhaustruct
    - dupword
    - musttag
    - forbidigo
    # tentative
    - revive
    - unparam
    - forcetypeassert
    - noctx
    - perfsprint
    - prealloc

linters-settings:
  cyclop:
    max-complexity: 12